/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d7fe7f9b-cd2a-41c3-bce1-4f89165f4a15",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_AouIZfC9T",
    "aws_user_pools_web_client_id": "7lh4a6u21eufaq307a4i9fqnuh",
    "oauth": {}
};


export default awsmobile;
